#include <stdio.h>
#include "stack.h"
int main()
{
    sStack *stack=NULL;
    int status=0;
    stack=StackInit();
    if(!stack)
    {
        printf("初始化栈失败\n");
    }
    status=StackEmpty(stack);
    if(status)
    {
        printf("栈为空\n");
    }
    else
    {
        printf("栈不为空\n");
    }
    status=Push(stack,11);
    if(status)
    {
        printf("压栈成功\n");
    }
    else
    {
        printf("压栈失败\n");
    }
    status=StackEmpty(stack);
    if(status)
    {
        printf("栈为空\n");
    }
    else
    {
        printf("栈不为空\n");
    }
    status=Push(stack,22);
    if(status)
    {
        printf("压栈成功\n");
    }
    else
    {
        printf("压栈失败\n");
    }
    status=StackLength(stack);
    printf("当前栈的长度为%d\n",status);
    status=Push(stack,33);
    if(status)
    {
        printf("压栈成功\n");
    }
    else
    {
        printf("压栈失败\n");
    }
    status=StackFull(stack);
    if(status)
    {
        printf("栈为满\n");
    }
    else
    {
        printf("栈不为满\n");
    }
    status=StackLength(stack);
    printf("当前栈的长度为%d\n",status);
    status=GetTop(stack);
    printf("当前栈的栈顶的值为%d\n",status);
    status=Push(stack,44);
    if(status)
    {
        printf("压栈成功\n");
    }
    else
    {
        printf("压栈失败\n");
    }
    status=StackFull(stack);
    if(status)
    {
        printf("栈为满\n");
    }
    else
    {
        printf("栈不为满\n");
    }
    //StackDisplay(stack);
    status=Push(stack,55);
    if(status)
    {
        printf("压栈成功\n");
    }
    else
    {
        printf("压栈失败\n");
    }
    status=StackFull(stack);
    if(status)
    {
        printf("栈为满\n");
    }
    else
    {
        printf("栈不为满\n");
    }
    status=StackLength(stack);
    printf("当前栈的长度为%d\n",status);
    status=GetTop(stack);
    printf("当前栈的栈顶的值为%d\n",status);
    status=Pop(stack);
    printf("当前取栈的栈顶的值为%d\n",status);
    status=StackFull(stack);
    if(status)
    {
        printf("栈为满\n");
    }
    else
    {
        printf("栈不为满\n");
    }
    status=StackLength(stack);
    printf("当前栈的长度为%d\n",status);
    status=GetTop(stack);
    printf("当前栈的栈顶的值为%d\n",status);
    StackClear(stack);
    status=StackEmpty(stack);
    if(status)
    {
        printf("栈为空\n");
    }
    else
    {
        printf("栈不为空\n");
    }
    printf("当前栈的长度为%d\n",status);
    StackDestory(stack);
    return 0;
}